/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UlasanRouteImport } from './routes/ulasan'
import { Route as DapurAdminIndexRouteImport } from './routes/dapur-admin.index'
import { Route as DapurAdminDashboardRouteImport } from './routes/dapur-admin.dashboard'
import { Route as DapurAdminResetPasswordRouteImport } from './routes/dapur-admin.reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasanRoute = UlasanRouteImport.update({
  id: '/ulasan',
  path: '/ulasan',
  getParentRoute: () => rootRouteImport,
} as any)
const DapurAdminIndexRoute = DapurAdminIndexRouteImport.update({
  id: '/dapur-admin/',
  path: '/dapur-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DapurAdminDashboardRoute = DapurAdminDashboardRouteImport.update({
  id: '/dapur-admin/dashboard',
  path: '/dapur-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DapurAdminResetPasswordRoute = DapurAdminResetPasswordRouteImport.update({
  id: '/dapur-admin/reset-password',
  path: '/dapur-admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ulasan': typeof UlasanRoute
  '/dapur-admin/dashboard': typeof DapurAdminDashboardRoute
  '/dapur-admin/reset-password': typeof DapurAdminResetPasswordRoute
  '/dapur-admin/': typeof DapurAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ulasan': typeof UlasanRoute
  '/dapur-admin/dashboard': typeof DapurAdminDashboardRoute
  '/dapur-admin/reset-password': typeof DapurAdminResetPasswordRoute
  '/dapur-admin': typeof DapurAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ulasan': typeof UlasanRoute
  '/dapur-admin/dashboard': typeof DapurAdminDashboardRoute
  '/dapur-admin/reset-password': typeof DapurAdminResetPasswordRoute
  '/dapur-admin/': typeof DapurAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ulasan'
    | '/dapur-admin/dashboard'
    | '/dapur-admin/reset-password'
    | '/dapur-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ulasan'
    | '/dapur-admin/dashboard'
    | '/dapur-admin/reset-password'
    | '/dapur-admin'
  id:
    | '__root__'
    | '/'
    | '/ulasan'
    | '/dapur-admin/dashboard'
    | '/dapur-admin/reset-password'
    | '/dapur-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UlasanRoute: typeof UlasanRoute
  DapurAdminDashboardRoute: typeof DapurAdminDashboardRoute
  DapurAdminResetPasswordRoute: typeof DapurAdminResetPasswordRoute
  DapurAdminIndexRoute: typeof DapurAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasan': {
      id: '/ulasan'
      path: '/ulasan'
      fullPath: '/ulasan'
      preLoaderRoute: typeof UlasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dapur-admin/': {
      id: '/dapur-admin/'
      path: '/dapur-admin'
      fullPath: '/dapur-admin/'
      preLoaderRoute: typeof DapurAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dapur-admin/dashboard': {
      id: '/dapur-admin/dashboard'
      path: '/dapur-admin/dashboard'
      fullPath: '/dapur-admin/dashboard'
      preLoaderRoute: typeof DapurAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dapur-admin/reset-password': {
      id: '/dapur-admin/reset-password'
      path: '/dapur-admin/reset-password'
      fullPath: '/dapur-admin/reset-password'
      preLoaderRoute: typeof DapurAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UlasanRoute: UlasanRoute,
  DapurAdminDashboardRoute: DapurAdminDashboardRoute,
  DapurAdminResetPasswordRoute: DapurAdminResetPasswordRoute,
  DapurAdminIndexRoute: DapurAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
